server:
  port: 8081

spring:
  application:
    name: eureka-discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka